# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - entraidapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: 'EntraID-FunctionApp-Client'
  DOTNET_VERSION: '10.0.x'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build "./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/EntraID-FunctionApp-Client.csproj" --configuration Release

      - name: dotnet publish
        run: dotnet publish "./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/EntraID-FunctionApp-Client.csproj" -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_09BC4006FDF242089BC764C25CC7087F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F840DAE93E174EC996CC39161AC41B81 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BDDA90BA74774EB085C697E123FD2E9D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'entraidapp'
          slot-name: 'Production'
          package: .
          